### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by Fornaxus** [worldanvil/worldanvil-bug-tracker#1135]
**World Anvil Username**: Emrath

**World / Campaign / RPG Character / Manuscript Title**: gods-of-order-article

**Feature**: text

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
The text is invisible, except when selected, in view mode.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/emrath-fornaxus/a/gods-of-order-article

**Expected behavior**
You don't see the text (aside from the headings) unless you select it.

**Screenshots**

![image](https://user-images.githubusercontent.com/108236680/177003960-7ad9f06a-746c-4efb-8542-24341b475550.png)

**Comment by iamromeo** [comment]
This is due to custom CSS of the world the following setting 

```css
body {
    background-image: url(/uploads/images/a6e5690….jpg) !important;
    color: rgba(241, 63, 63, 0) !important;
}
```

Sets your text invisible. This is not a bug it is a user set value
