### ISSUE TITLE
FontAwesome's flip/rotate classes don't seem to apply; fix included

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#597]
**World Anvil Username**:
Hanhula

**World / Campaign / RPG Character / Manuscript Title**:
Istralar, but the bug was found on Anhult (sage George's  world)

**Feature**: 
FontAwesome / World CSS

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/anhult/a/diondair-malairt

**Describe the Issue**

FontAwesome adds utility classes for rotating and flipping its fonts. However, these don't seem to apply on WorldAnvil. This seems to be because they're applying the CSS rotation/etc to the main class when FA is shoving their content in a :before, and the :before needs to be an inline-block to get the transformation.

**To Reproduce**
1. Enter [section:fas fa-wind fa-flip-horizontal] [/section] on a page
2. View page
3. Amend CSS with my fix

**Expected behavior**

Wind symbol is flipped when flip class is added 

**Code fix**
```css
.user-css .fa-flip-horizontal:before {
    display: inline-block;
    -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)"
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
}
```
This should fix it; it's an exact copy of the fa-flip-horizontal code but applied to :before and with an inline-block added.
If this fix is the only thing that needs to be done & there's not some better way of doing it, then copying the CSS from all of the classes [here ](https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/rotating-icons) with the same tweaks would work the same.
