### ISSUE TITLE
List become nested when embedding an rendered fragment variable

### ISSUE THREAD

**Issue by Linnitry** [worldanvil/worldanvil-bug-tracker#766]
**World Anvil Username**: Linnitry

**World**: Silverdawn

**Feature**: Variable Collection, Rendered Fragment, Spoiler (accordion), Embedded text, BBCode

**Describe the Issue**
When creating a rendered fragment varialble and using BBCode to make lists, the list become nested if the fragment is embeded into an article

**To Reproduce**
1. Go to Variables, create a new rendered fragment. Create a list or use my example
```
[h1]Arena Rules[/h1]
[ul]
[li]If you place a bet, and win, your bet is doubled.[/li]
[li]You cannot be killed in the arena through PvP. Medics are on standby.[/li]
[li]Feel free to gamble on the fighters.[/li]
[/ul]
```
2. Copy the variable tag
3. Go to Configuration
4. In "World Introduction / Description, create an accordion layout or use my example
```
[left][container:][h4|splr-acch]
[spoiler][var:myRenderFragmentTag] | Render Fragment Example [/spoiler]
[spoiler]Text | Label One [/spoiler]
[spoiler]Text | Label Two [/spoiler]
[spoiler]Text | Label Three [/spoiler]
[/h4][/container][/left]
```
5. Make sure one of the entries in the accordion is setup to embedd the render fragmen variable we created earlier. For example [var:myRenderFragmentTag]
6. View the page
7. Open the CSS editor
8. Paste in this CSS (The actual CSS is not relevant for the bug, it's just to have the accordion behave as intended. I tried ripping all custom CSS out but the problem persisted. Worth double-checking ofc)
```CSS
/*───────────────────────*/
/*        Acordion       */
/*───────────────────────*/
/* first, we need to reset the h5 heading so it doesn't affect the spoiler text */
/* this is also where you decide how wide you want your spoiler accordion to be */
/* use either a percentage or some absolute units like px or em */
.user-css h5#splr-acch {
 text-transform: none;
 font-weight: normal;
 font-size: inherit;
 margin: auto;
 padding: 10px;
 line-height: inherit;
 display: block;
}
 
/* the spoiler button has some classes automatically applied. We need to change those */
.user-css h5#splr-acch a.spoiler-button {
 display: inline-flex;
 justify-content: center;
 align-items: center;
 text-align: center;
 font-size: 1.1em; 

 padding: 0px 0px;
 margin: 0px;
 border: 1px solid;
 border-bottom: 0px;

 color: #730202!important;
 border-color: #A6761C; 
 background-color: #E5DBB7; 

 width: 100%;
 height: 30px;
}
 
/* we'd like the top button to have rounded top corners */
.user-css h5#splr-acch a.spoiler-button:first-of-type {
 border-top-right-radius: 10px;
 border-top-left-radius: 10px;
 border-bottom: 0px;
}
 
/* we'd like the last button to have rounded bottom corners...and it will, after it has 
 been opened and re-closed once. */
.user-css h5#splr-acch a.spoiler-button.collapsed:last-of-type {
 border-bottom-right-radius: 10px;
 border-bottom-left-radius: 10px;
 border-bottom: 1px solid #A6761C;
}
 
/* here's where we style the content of each spoiler */
.user-css h5#splr-acch div.spoiler-content {
 margin: 0px;
 border-radius: 0px;
 font-size: 1.3em;
 text-justify: left;
 border: 1px solid #A6761C;
 background-color: #F2F2F
}
 
/* and of course, that last spoiler panel should have rounded corners when open */
.user-css h5#splr-acch [class^=spoiler-conta]:last-child div.spoiler-content {
 border-bottom-right-radius: 10px;
 border-bottom-left-radius: 10px;
}

```
9. Save CSS and update page. Open accordion. It MAY look correct at this point.. but let's not be fooled ;)
10. Open the inspector and locate the list, notice that there's no nested list. It would look something like the example below (this is only to see what happens)
```html
<ul data-uw-styling-context="true">
<li data-uw-styling-context="true">Label One</li>
<li data-uw-styling-context="true">Label Two</li>
<li data-uw-styling-context="true">Label Three</li>
</ul>

```
11. Go back to the Variable and add a new element that makes it update.
12. Go back to the front page and update, check accordion again
13. The list bullets should now have changed to open circles instead of filled.
14. Inspect the html again and the list have been nested and look something like this:
```html
<ul data-uw-styling-context="true">
<ul data-uw-styling-context="true">
<li data-uw-styling-context="true">Label One</li>
<li data-uw-styling-context="true">Label Two</li>
<li data-uw-styling-context="true">Label Three</li>
</ul>
</ul>

```

**Expected behavior**
The expected behaviour is that the list don't become nested

**Screenshots**
Open Cirlces that we don't want
![image](https://user-images.githubusercontent.com/95034809/146824383-31cb6bb5-a427-4723-b264-66ee8d2c594e.png)

HTML showing how the list have added a nested layer
![image](https://user-images.githubusercontent.com/95034809/146824566-dcd31c17-4d44-487e-9803-441ecad97afb.png)

Best Regards,
L
